// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqrRySYEXZmu4_09qWPR-yM_5KVmRR3ZM',
    appId: '1:340725366476:web:5cd5ff7d402b43dc27cc69',
    messagingSenderId: '340725366476',
    projectId: 'hands4events-cd714',
    authDomain: 'hands4events-cd714.firebaseapp.com',
    storageBucket: 'hands4events-cd714.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXJhsCR7OfJFdhfAtDZ3xpk1Pi-di2aa4',
    appId: '1:340725366476:android:ca0f8f9c3ec629c727cc69',
    messagingSenderId: '340725366476',
    projectId: 'hands4events-cd714',
    storageBucket: 'hands4events-cd714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUuaCPhPpPoU5aOtW47-Li-5enoACcl5U',
    appId: '1:340725366476:ios:bdaa64150c5b642827cc69',
    messagingSenderId: '340725366476',
    projectId: 'hands4events-cd714',
    storageBucket: 'hands4events-cd714.firebasestorage.app',
    iosBundleId: 'com.example.hands4events',
  );
}
