class Traducciones {
  static const Map<String, Map<String, String>> _t = {
    'es': {
      'nav_escritorio': 'Escritorio',
      'nav_ofertas': 'Ofertas',
      'nav_eventos': 'Eventos',
      'nav_perfil': 'Perfil',
      'proximos_eventos': 'Próximos eventos',
      'notificaciones': 'Notificaciones',
      'sin_eventos': 'No tienes eventos próximos asignados',
      'sin_notificaciones': 'No tienes notificaciones nuevas',
      'en_curso': 'EN CURSO',
      'sin_eventos_dia': 'No hay eventos para este día',
      'fichaje': 'Fichaje',
      'fichar_entrada': 'FICHAR ENTRADA',
      'fichar_salida': 'FICHAR SALIDA',
      'pausar': 'PAUSAR',
      'reanudar': 'REANUDAR',
      'fichaje_completado': 'Fichaje completado',
      'estado_actual': 'Estado actual',
      'historial': 'Historial',
      'sin_historial': 'No hay fichajes anteriores para este evento',
      'tiempo_trabajado': 'Tiempo trabajado',
      'entrada': 'Entrada',
      'salida': 'Salida',
      'pausas': 'Pausas',
      'gps_info': 'La ubicación se registra al fichar entrada y salida',
      'estado_no_iniciado': 'No iniciado',
      'estado_en_curso': 'Fichaje en curso',
      'estado_pausado': 'Fichaje en pausa',
      'estado_finalizado': 'Fichaje finalizado',
      'perfil': 'Perfil',
      'informacion_personal': 'INFORMACIÓN PERSONAL',
      'configuracion': 'CONFIGURACIÓN',
      'otros': 'OTROS',
      'telefono': 'Teléfono',
      'direccion': 'Dirección',
      'idioma': 'Idioma',
      'notificaciones_config': 'Notificaciones',
      'gestionar_preferencias': 'Gestionar preferencias',
      'nominas_vacaciones': 'Nóminas y vacaciones',
      'ver_nominas': 'Ver nóminas y solicitar vacaciones',
      'cerrar_sesion': 'Cerrar sesión',
      'cerrar_sesion_confirm': '¿Cerrar sesión?',
      'cerrar_sesion_msg': 'Se cerrará tu sesión y volverás a la pantalla de inicio.',
      'cancelar': 'Cancelar',
      'notif_activadas': 'Activadas',
      'notif_activadas_desc': 'Recibirás todas las notificaciones',
      'notif_desactivadas': 'Desactivadas',
      'notif_desactivadas_desc': 'No recibirás notificaciones',
      'notif_silenciar': 'Silenciar notificaciones',
      'notif_silenciar_desc': 'Silenciar temporalmente',
      'notif_silenciar_por': 'Silenciar por:',
      'guardar': 'Guardar',
      '1h': '1 hora',
      '8h': '8 horas',
      '24h': '24 horas',
      'hasta_manana': 'Hasta mañana',
      'seleccionar_idioma': 'Seleccionar idioma',
      'buscar_idioma': 'Buscar idioma...',
      'confirmar_cambio': 'Confirmar cambio',
      'nominas': 'Nóminas y vacaciones',
      'vacaciones': 'Vacaciones',
      'dias_disponibles': 'DÍAS DISPONIBLES',
      'solicitar_vacaciones': 'Solicitar vacaciones',
      'sin_nominas': 'No hay nóminas disponibles',
      'no_configurado': 'No configurado',
      'no_configurada': 'No configurada',
      'escritorio': 'Escritorio',
      'info_evento': 'Información del Evento',
      'fecha_label': 'Fecha',
      'hora_label': 'Hora',
      'ubicacion_label': 'Ubicación',
      'descripcion_label': 'Descripción',
      'sin_descripcion': 'Sin descripción disponible.',
      'tu_asignacion': 'Tu Asignación',
      'cobro_hora': 'Cobro por Hora',
      'rol_asignado': 'Rol Asignado',
      'tiempo_estimado_label': 'Tiempo Estimado',
      'sin_especificar': 'Sin especificar',
      'hora_unidad': 'hora',
      'horas_unidad': 'horas',
      'fichaje_disponible_en': 'Disponible en',
      'fichaje_evento_terminado': 'El evento ha finalizado',
      'fichaje_evento_no_iniciado': 'El evento aún no ha comenzado',
      'editar_direccion': 'Editar dirección',
      'busca_direccion': 'Busca tu dirección...',
      'busca_para_ver_mapa': 'Busca una dirección para ver el mapa',
      'seccion_nominas': 'Nóminas',
      'solicitudes_revisadas': 'Las solicitudes serán revisadas por la empresa',
      'mis_solicitudes': 'MIS SOLICITUDES',
      'todos': 'Todos',
      'filtro_en_curso': 'En curso',
      'filtro_proximos': 'Próximos',
      'filtro_pasados': 'Pasados',
      'error_cargar_eventos': 'Error al cargar eventos',
      'reintentar': 'Reintentar',
      'sin_eventos_categoria': 'No hay eventos en esta categoría',
      'no_se_puede_abrir': 'No se puede abrir el documento',
      // Login
      'bienvenido': '¡Bienvenido! Iniciando sesión...',
      'inicio_sesion_etiqueta': 'INICIO DE SESIÓN',
      'iniciar_sesion': 'Iniciar Sesión',
      'subtitulo_login': 'Accede a tu cuenta corporativa para gestionar eventos y\ncoordinar equipos de trabajo.',
      'email_usuario': 'Correo electrónico o nombre de usuario',
      'error_campo_email': 'Por favor ingresa tu correo o usuario',
      'contrasena': 'Contraseña',
      'error_campo_contrasena': 'Por favor ingresa tu contraseña',
      'error_contrasena_corta': 'La contraseña debe tener al menos 6 caracteres',
      'olvidaste_contrasena': '¿Olvidaste tu contraseña?',
      'error_credenciales': 'Correo o contraseña incorrectos',
      'error_muchos_intentos': 'Demasiados intentos. Espera unos minutos',
      'error_sin_conexion': 'Sin conexión a internet',
      'error_sesion_gen': 'Error al iniciar sesión. Inténtalo de nuevo',
      // Fichaje
      'fichaje_iniciado': 'Fichaje iniciado correctamente',
      'fichaje_finalizado_ok': 'Fichaje finalizado correctamente',
      'error_fichar_entrada': 'Error al fichar entrada',
      'error_pausar': 'Error al pausar',
      'error_reanudar': 'Error al reanudar',
      'error_fichar_salida': 'Error al fichar salida',
      // Chat
      'chat_subtitulo': 'Chat del evento',
      'info_equipo': 'Información del equipo',
      'ver_miembros': 'Ver miembros del equipo',
      'chat_no_disponible': 'Chat no disponible',
      'primer_mensaje': 'Sé el primero en escribir',
      'escribe_mensaje': 'Escribe un mensaje...',
      // Equipo
      'equipo_evento_titulo': 'Equipo del Evento',
      'sin_equipo': 'No hay información de equipo disponible',
      'equipo_no_cargado': 'No se pudo cargar el equipo',
      'sin_rol': 'Sin rol asignado',
      'sin_telefono': 'Sin teléfono',
      'error_llamada': 'No se puede realizar la llamada',
      'miembros_equipo': '{n} miembro{s} en el equipo',
      // Días de la semana
      'dia_lunes': 'Lunes',
      'dia_martes': 'Martes',
      'dia_miercoles': 'Miércoles',
      'dia_jueves': 'Jueves',
      'dia_viernes': 'Viernes',
      'dia_sabado': 'Sábado',
      'dia_domingo': 'Domingo',
      // Modal vacaciones
      'seleccionar_fecha': 'Seleccionar fecha',
      'selecciona_fechas_error': 'Selecciona las fechas de inicio y fin',
      'sin_dias_suficientes': 'No tienes suficientes días disponibles',
      'solicitud_enviada': 'Solicitud enviada. Quedará pendiente de aprobación.',
      'error_solicitud': 'Error al enviar la solicitud',
      'dias_disponibles_label': 'Días disponibles',
      'fecha_inicio_label': 'Fecha de inicio',
      'fecha_fin_label': 'Fecha de fin',
      'observaciones_label': 'Observaciones',
      'comentario_opcional': 'Añade un comentario opcional',
      'enviar_solicitud': 'Enviar solicitud',
      'solicitando_prefijo': 'Solicitando ',
      'dia_singular': 'día',
      'dias_plural': 'días',
      'restarian': ' → Restarían ',
      'solicitados_label': ' solicitados, ',
      'disponibles_label': ' disponibles',
      // Modal notificaciones
      'notif_msg_activadas': 'Notificaciones activadas',
      'notif_msg_desactivadas': 'Notificaciones desactivadas',
      'notif_msg_silenciadas': 'Notificaciones silenciadas',
      'error_guardar_config': 'Error al guardar configuración',
      // Modal dirección
      'toca_mapa': 'Toca el mapa para marcar tu dirección',
      'direccion_invalida': 'Introduce una dirección válida',
      'direccion_actualizada': 'Dirección actualizada correctamente',
      'error_actualizar_direccion': 'Error al actualizar la dirección',
      'guardar_cambios': 'Guardar cambios',
      // Nóminas vacaciones
      'acumulados_label': 'acumulados',
      'usados_label': 'usados',
      // Dashboard
      'ultima_nomina': 'Última nómina',
      // Detalle evento
      'ir_chat': 'CHAT',
      'grupo_no_creado': 'GRUPO NO CREADO',
      'grupo_aviso': 'El grupo aún no está creado',
      'ver_historico': 'VER HISTÓRICO',
      'evento_finalizado_lectura': 'Evento finalizado · solo lectura',
      // Perfil nominas
      'ver_mis_nominas': 'Ver mis nóminas',
      // Modal idioma
      'idioma_es': 'Español',
      'idioma_en': 'Inglés',
      'idioma_cambiado_a': 'Idioma cambiado a',
      'error_cambiar_idioma': 'Error al cambiar el idioma',
      // Modal avatar
      'seleccionar_avatar': 'Seleccionar avatar',
      'galeria': 'Galería',
      'camara': 'Cámara',
      'avatar_predefinido': 'O elige un avatar predefinido',
      'usar_iniciales': 'Usar iniciales del nombre',
      'avatar_actualizado': 'Avatar actualizado correctamente',
      'error_actualizar_avatar': 'Error al actualizar el avatar',
      'guardar_avatar': 'Guardar avatar',
      // Recuperar contraseña
      'recuperar_contrasena': 'Recuperar contraseña',
      'correo_no_registrado': 'No existe ninguna cuenta con ese correo electrónico',
      'correo_enviado_titulo': '¡Correo enviado!',
      'introduce_tu_correo': 'Introduce tu correo electrónico',
      'correo_recibido_desc': 'Si el correo está registrado en nuestra plataforma, recibirás las instrucciones en tu bandeja de entrada.',
      'instrucciones_desc': 'Te enviaremos instrucciones para restablecer tu contraseña.',
      'correo_electronico': 'Correo electrónico',
      'ingresa_correo_error': 'Por favor ingresa tu correo electrónico',
      'correo_invalido_error': 'Por favor ingresa un correo válido',
      'enviar_instrucciones': 'Enviar instrucciones',
      'redirigiendo_login': 'Redirigiendo al inicio de sesión...',
      'error_enviar_correo': 'Error al enviar el correo. Inténtalo de nuevo',
      'error_correo_no_encontrado': 'No existe una cuenta con ese correo',
      // Modal editar teléfono
      'editar_telefono': 'Editar teléfono',
      'numero_telefono': 'Número de teléfono',
      'telefono_digitos_error': 'Introduce 9 dígitos válidos',
      'telefono_actualizado': 'Teléfono actualizado correctamente',
      'error_actualizar_telefono': 'Error al actualizar el teléfono',
      'telefono_info': 'Este número se usará para contactarte en caso de emergencias o cambios de última hora en los eventos.',
      // Chat - ubicación
      'compartir_ubicacion': 'Compartir ubicación',
      'ubicacion_compartida': 'Ubicación',
      'abrir_maps': 'Abrir en Maps',
      'gps_desactivado': 'Los servicios de ubicación están desactivados',
      'seleccionar_ubicacion': 'Seleccionar ubicación',
      'confirmar_ubicacion': 'Confirmar y enviar',
      'adjuntar_imagen': 'Adjuntar imagen',
      'error_traduccion': 'Error de traducción. Activa "Cloud Translation API" en Google Cloud Console',
      // Chat - traducción
      'traducir_mensajes': 'Traducir mensajes',
      // Chat - interacciones (responder, editar, borrar)
      'respondiendo_a': 'Respondiendo a',
      'editando_mensaje': 'Editando mensaje',
      'editar': 'Editar',
      'eliminar': 'Eliminar',
      'confirmar_eliminar': '¿Eliminar este mensaje?',
      'mensaje_editado': 'editado',
      'error_editar': 'Error al editar el mensaje',
      'error_eliminar': 'Error al eliminar el mensaje',
      // ── Panel admin: shell y sidebar ──
      'admin_panel': 'Panel Admin',
      'admin_inicio': 'Inicio',
      'admin_trabajadores': 'Trabajadores',
      'admin_eventos': 'Eventos',
      'admin_nominas': 'Nóminas',
      'admin_logout_msg': '¿Seguro que quieres cerrar sesión?',
      // ── Panel admin: dashboard ──
      'admin_resumen': 'Resumen',
      'admin_actualizar': 'Actualizar',
      'admin_kpi_trabajadores': 'Trabajadores activos',
      'admin_kpi_eventos': 'Eventos próximos (7 días)',
      'admin_kpi_horas': 'Horas fichadas este mes',
      'admin_kpi_nominas': 'Nóminas pendientes de enviar',
      'admin_proximos_eventos': 'Próximos eventos',
      'admin_sin_proximos': 'No hay eventos próximos',
      'admin_error_datos': 'No se pudieron cargar los datos',
      'admin_reintentar': 'Reintentar',
      'admin_asignados': 'asignados',
      // ── Panel admin: trabajadores ──
      'w_nuevo': 'Nuevo trabajador',
      'w_error_cargar': 'Error al cargar trabajadores',
      'w_buscar': 'Buscar por nombre…',
      'w_sin_resultados': 'Ningún trabajador coincide con la búsqueda',
      'w_col_nombre': 'NOMBRE',
      'w_col_email': 'EMAIL',
      'w_col_telefono': 'TELÉFONO',
      'w_col_estado': 'ESTADO',
      'w_activo': 'Activo',
      'w_inactivo': 'Inactivo',
      'w_gestionar': 'Gestionar',
      'w_sin_workers': 'Todavía no hay trabajadores',
      'w_crear_primero': 'Crear el primero',
      'w_gestionar_titulo': 'Gestionar trabajador',
      'w_nombre': 'Nombre *',
      'w_apellidos': 'Apellidos',
      'w_telefono': 'Teléfono',
      'w_dni': 'DNI',
      'w_activo_toggle': 'Trabajador activo',
      'w_inactivo_toggle': 'Trabajador inactivo',
      'w_campo_obligatorio': 'Campo obligatorio',
      'w_min_password': 'Mínimo 6 caracteres',
      'w_formato_telefono': 'Formato: 6XXXXXXXX',
      'w_formato_dni': 'Formato: 12345678A',
      'w_guardar_cambios': 'Guardar cambios',
      'w_error_guardar': 'Error al guardar. Inténtalo de nuevo.',
      'w_error_eliminar_op': 'Error al eliminar. Inténtalo de nuevo.',
      'w_eliminar_titulo': 'Eliminar trabajador',
      'w_eliminar_pre': '¿Seguro que quieres eliminar a ',
      'w_eliminar_post': '? Esta acción no se puede deshacer.',
      'w_datos_ok': 'Datos actualizados correctamente',
      'w_eliminado': 'Trabajador eliminado',
      'w_email': 'Email *',
      'w_password': 'Contraseña *',
      'w_crear': 'Crear trabajador',
      'w_err_email_uso': 'Ese email ya está registrado.',
      'w_err_email_inv': 'El email no es válido.',
      'w_err_pass_debil': 'La contraseña es demasiado débil.',
      'w_err_crear': 'Error al crear el trabajador. Inténtalo de nuevo.',
      'w_creado': 'Trabajador creado',
      'w_email_label': 'Email',
      'w_password_label': 'Contraseña',
      'w_descargar_ticket': 'Descargar ticket PDF',
      'w_cerrar': 'Cerrar',
      'w_generar_password': 'Generar nueva contraseña',
      // ── Panel admin: eventos (lista + formulario) ──
      'ev_estado_borrador': 'Borrador',
      'ev_estado_publicado': 'Publicado',
      'ev_estado_activo': 'Activo',
      'ev_estado_finalizado': 'Finalizado',
      'ev_filtro_todos': 'Todos',
      'ev_filtro_borradores': 'Borradores',
      'ev_filtro_publicados': 'Publicados',
      'ev_filtro_activos': 'Activos',
      'ev_filtro_finalizados': 'Finalizados',
      'ev_nuevo': 'Nuevo evento',
      'ev_error_cargar': 'Error al cargar eventos',
      'ev_fecha': 'Fecha',
      'ev_sin_resultados': 'Ningún evento coincide con los filtros',
      'ev_confirmados': 'confirmados',
      'ev_pendientes_tooltip': 'Postulaciones pendientes de revisar',
      'ev_pendiente': 'pendiente',
      'ev_pendientes': 'pendientes',
      'ev_editar_tooltip': 'Editar evento',
      'ev_eliminar_tooltip': 'Eliminar evento',
      'ev_cambiar_estado': 'Cambiar estado',
      'ev_eliminar_titulo': 'Eliminar evento',
      'ev_eliminar_msg': 'Se borrarán los mensajes del chat y se notificará a los trabajadores asignados.',
      'ev_eliminado_pre': 'Evento "',
      'ev_eliminado_post': '" eliminado',
      'ev_sin_eventos': 'Todavía no hay eventos',
      'ev_crear_primero': 'Crear el primero',
      'ev_err_fecha_hora': 'Debes seleccionar fecha y hora.',
      'ev_err_duracion': 'La duración debe ser mayor que 0.',
      'ev_err_plaza': 'Define al menos una plaza en algún rol.',
      'ev_guard_pre': 'No puedes dejar el rol "',
      'ev_guard_mid': '" por debajo de sus ',
      'ev_guard_post': ' confirmados. Sube las plazas o quita integrantes primero.',
      'ev_err_guardar': 'No se pudo guardar el evento. Inténtalo de nuevo.',
      'ev_editar_titulo': 'Editar evento',
      'ev_sec_detalles': 'Detalles del evento',
      'ev_campo_nombre': 'Nombre del evento *',
      'ev_campo_desc': 'Descripción (opcional)',
      'ev_campo_ubicacion': 'Ubicación *',
      'ev_campo_duracion': 'Duración (h) *',
      'ev_crear_evento': 'Crear evento',
      'ev_sec_plazas': 'Plazas por rol',
      'ev_plazas_help': '¿Cuántos trabajadores necesitas de cada rol?',
      'ev_sec_estado': 'Estado',
      'ev_fecha_req': 'Fecha *',
      'ev_hora_req': 'Hora *',
      'ev_marcado_pre': 'Evento marcado como ',
      'ev_err_estado': 'No se pudo cambiar el estado',
      'ev_volver': 'Volver a la lista',
      'ev_quitar_fecha': 'Quitar filtro de fecha',
      'ev_ver_postulaciones': 'Ver postulaciones',
      'ev_ver_fichajes': 'Ver fichajes',
      // ── Panel admin: postulaciones / gestion del equipo ──
      'pl_volver': 'Volver',
      'pl_titulo': 'Postulaciones',
      'pl_confirmados_sec': 'CONFIRMADOS',
      'pl_pendientes_sec': 'PENDIENTES',
      'pl_anadir': 'Añadir integrante',
      'pl_anadir_btn': 'Añadir',
      'pl_ver_historico': 'Ver histórico del chat',
      'pl_abrir_chat': 'Abrir chat del grupo',
      'pl_chat_no_disp': 'Chat no disponible (grupo no creado)',
      'pl_sin_pendientes': 'No hay postulaciones pendientes',
      'pl_sin_confirmados': 'Aún no hay nadie confirmado',
      'pl_quitar': 'Quitar',
      'pl_quitar_titulo': 'Quitar integrante',
      'pl_quitar_pre': '¿Quitar a ',
      'pl_quitar_post': ' del evento? Se liberará su plaza y su postulación quedará descartada.',
      'pl_quitado': 'Integrante quitado',
      'pl_err_quitar': 'No se pudo quitar',
      'pl_sin_plazas': 'No hay plazas libres; edita el evento para añadir plazas',
      'pl_sin_workers': 'No hay más trabajadores para añadir',
      'pl_trabajador_label': 'Trabajador',
      'pl_rol_label': 'Rol (con plaza libre)',
      'pl_anadido': 'Integrante añadido',
      'pl_rol_completo': 'Rol completo; edita el evento para añadir plazas',
      'pl_err_anadir': 'No se pudo añadir',
      'pl_trabajador': 'Trabajador',
      'pl_descartar': 'Descartar',
      'pl_confirmar': 'Confirmar',
      'pl_confirmado_ok': 'Trabajador confirmado',
      'pl_err_confirmar': 'No se pudo confirmar',
      'pl_descartada': 'Postulación descartada',
      'pl_err_descartar': 'No se pudo descartar',
      'pl_sin_plazas_evento': 'Este evento no define plazas por rol.',
      'pl_confirmados_conteo': 'confirmados',
      // Activación del grupo (activar_evento.dart)
      'pl_crear_grupo': 'Crear grupo',
      'pl_activar_completo': 'El equipo está completo. Se creará el grupo y el evento pasará a activo (sale del feed y se abre el chat).',
      'pl_activar_faltan': 'Aún faltan plazas por cubrir:',
      'pl_faltan': 'faltan',
      'pl_activar_pregunta': '¿Crear el grupo igualmente? El evento saldrá del feed.',
      'pl_grupo_creado': 'Grupo creado: evento activo',
      'pl_err_crear_grupo': 'No se pudo crear el grupo',
      // ── Panel admin: nóminas ──
      'nom_calculando': 'Calculando horas y sueldos...',
      'nom_mes': 'Mes',
      'nom_anio': 'Año',
      'nom_calcular': 'Calcular',
      'nom_instr1': 'Selecciona un mes y pulsa "Calcular"',
      'nom_instr2': 'Verás qué trabajadores han fichado ese mes\ny podrás enviarles su nómina.',
      'nom_sin_trabajo': 'Ningún trabajador ha trabajado en',
      'nom_sin_trabajo2': 'Solo aparecen trabajadores con fichajes finalizados en ese mes.',
      'nom_trabajadores_en': 'trabajador(es) en',
      'nom_visible': 'Las nóminas enviadas quedan visibles en la app del trabajador.',
      'nom_enviar_todas': 'Enviar todas',
      'nom_todas_enviadas': 'Todas enviadas',
      'nom_trabajadas': 'trabajadas',
      'nom_eventos_count': 'evento(s)',
      'nom_neto': 'neto',
      'nom_bruto': 'bruto',
      'nom_enviar': 'Enviar nómina',
      'nom_descargar_tooltip': 'Descargar PDF sin enviar',
      'nom_bruto_label': 'Bruto:',
      'nom_neto_label': 'Neto:',
      'nom_deducciones': 'IRPF 15% + SS 6.35%',
      'nom_enviada_pre': 'Nómina de ',
      'nom_enviada_post': ' enviada correctamente',
    },
    'en': {
      'nav_escritorio': 'Dashboard',
      'nav_ofertas': 'Offers',
      'nav_eventos': 'Events',
      'nav_perfil': 'Profile',
      'proximos_eventos': 'Upcoming events',
      'notificaciones': 'Notifications',
      'sin_eventos': 'No upcoming events assigned',
      'sin_notificaciones': 'No new notifications',
      'en_curso': 'ONGOING',
      'sin_eventos_dia': 'No events for this day',
      'fichaje': 'Time tracking',
      'fichar_entrada': 'CLOCK IN',
      'fichar_salida': 'CLOCK OUT',
      'pausar': 'PAUSE',
      'reanudar': 'RESUME',
      'fichaje_completado': 'Time tracking completed',
      'estado_actual': 'Current status',
      'historial': 'History',
      'sin_historial': 'No previous records for this event',
      'tiempo_trabajado': 'Time worked',
      'entrada': 'Clock in',
      'salida': 'Clock out',
      'pausas': 'Breaks',
      'gps_info': 'Location is recorded when clocking in and out',
      'estado_no_iniciado': 'Not started',
      'estado_en_curso': 'In progress',
      'estado_pausado': 'On break',
      'estado_finalizado': 'Completed',
      'perfil': 'Profile',
      'informacion_personal': 'PERSONAL INFORMATION',
      'configuracion': 'SETTINGS',
      'otros': 'OTHER',
      'telefono': 'Phone',
      'direccion': 'Address',
      'idioma': 'Language',
      'notificaciones_config': 'Notifications',
      'gestionar_preferencias': 'Manage preferences',
      'nominas_vacaciones': 'Payroll & holidays',
      'ver_nominas': 'View payslips and request holidays',
      'cerrar_sesion': 'Sign out',
      'cerrar_sesion_confirm': 'Sign out?',
      'cerrar_sesion_msg': 'Your session will be closed and you will return to the login screen.',
      'cancelar': 'Cancel',
      'notif_activadas': 'Enabled',
      'notif_activadas_desc': 'You will receive all notifications',
      'notif_desactivadas': 'Disabled',
      'notif_desactivadas_desc': 'You will not receive notifications',
      'notif_silenciar': 'Mute notifications',
      'notif_silenciar_desc': 'Temporarily mute',
      'notif_silenciar_por': 'Mute for:',
      'guardar': 'Save',
      '1h': '1 hour',
      '8h': '8 hours',
      '24h': '24 hours',
      'hasta_manana': 'Until tomorrow',
      'seleccionar_idioma': 'Select language',
      'buscar_idioma': 'Search language...',
      'confirmar_cambio': 'Confirm change',
      'nominas': 'Payroll & holidays',
      'vacaciones': 'Holidays',
      'dias_disponibles': 'AVAILABLE DAYS',
      'solicitar_vacaciones': 'Request holidays',
      'sin_nominas': 'No payslips available',
      'no_configurado': 'Not configured',
      'no_configurada': 'Not configured',
      'escritorio': 'Dashboard',
      'info_evento': 'Event Information',
      'fecha_label': 'Date',
      'hora_label': 'Time',
      'ubicacion_label': 'Location',
      'descripcion_label': 'Description',
      'sin_descripcion': 'No description available.',
      'tu_asignacion': 'Your Assignment',
      'cobro_hora': 'Hourly Rate',
      'rol_asignado': 'Assigned Role',
      'tiempo_estimado_label': 'Estimated Time',
      'sin_especificar': 'Not specified',
      'hora_unidad': 'hour',
      'horas_unidad': 'hours',
      'fichaje_disponible_en': 'Available in',
      'fichaje_evento_terminado': 'The event has ended',
      'fichaje_evento_no_iniciado': 'The event has not started yet',
      'editar_direccion': 'Edit address',
      'busca_direccion': 'Search your address...',
      'busca_para_ver_mapa': 'Search an address to view the map',
      'seccion_nominas': 'Payroll',
      'solicitudes_revisadas': 'Requests will be reviewed by the company',
      'mis_solicitudes': 'MY REQUESTS',
      'todos': 'All',
      'filtro_en_curso': 'Ongoing',
      'filtro_proximos': 'Upcoming',
      'filtro_pasados': 'Past',
      'error_cargar_eventos': 'Error loading events',
      'reintentar': 'Retry',
      'sin_eventos_categoria': 'No events in this category',
      'no_se_puede_abrir': 'Cannot open the document',
      // Login
      'bienvenido': 'Welcome! Logging in...',
      'inicio_sesion_etiqueta': 'LOG IN',
      'iniciar_sesion': 'Log In',
      'subtitulo_login': 'Access your corporate account to manage events and\ncoordinate work teams.',
      'email_usuario': 'Email or username',
      'error_campo_email': 'Please enter your email or username',
      'contrasena': 'Password',
      'error_campo_contrasena': 'Please enter your password',
      'error_contrasena_corta': 'Password must be at least 6 characters',
      'olvidaste_contrasena': 'Forgot your password?',
      'error_credenciales': 'Incorrect email or password',
      'error_muchos_intentos': 'Too many attempts. Please wait a few minutes',
      'error_sin_conexion': 'No internet connection',
      'error_sesion_gen': 'Login error. Please try again',
      // Fichaje
      'fichaje_iniciado': 'Clock-in recorded successfully',
      'fichaje_finalizado_ok': 'Clock-out recorded successfully',
      'error_fichar_entrada': 'Error recording clock-in',
      'error_pausar': 'Error pausing',
      'error_reanudar': 'Error resuming',
      'error_fichar_salida': 'Error recording clock-out',
      // Chat
      'chat_subtitulo': 'Event chat',
      'info_equipo': 'Team information',
      'ver_miembros': 'View team members',
      'chat_no_disponible': 'Chat not available',
      'primer_mensaje': 'Be the first to write',
      'escribe_mensaje': 'Write a message...',
      // Equipo
      'equipo_evento_titulo': 'Event Team',
      'sin_equipo': 'No team information available',
      'equipo_no_cargado': 'Could not load the team',
      'sin_rol': 'No role assigned',
      'sin_telefono': 'No phone',
      'error_llamada': 'Cannot make the call',
      'miembros_equipo': '{n} member{s} in the team',
      // Días de la semana
      'dia_lunes': 'Monday',
      'dia_martes': 'Tuesday',
      'dia_miercoles': 'Wednesday',
      'dia_jueves': 'Thursday',
      'dia_viernes': 'Friday',
      'dia_sabado': 'Saturday',
      'dia_domingo': 'Sunday',
      // Modal vacaciones
      'seleccionar_fecha': 'Select date',
      'selecciona_fechas_error': 'Select the start and end dates',
      'sin_dias_suficientes': 'Not enough available days',
      'solicitud_enviada': 'Request sent. It will be pending approval.',
      'error_solicitud': 'Error sending the request',
      'dias_disponibles_label': 'Available days',
      'fecha_inicio_label': 'Start date',
      'fecha_fin_label': 'End date',
      'observaciones_label': 'Notes',
      'comentario_opcional': 'Add an optional comment',
      'enviar_solicitud': 'Send request',
      'solicitando_prefijo': 'Requesting ',
      'dia_singular': 'day',
      'dias_plural': 'days',
      'restarian': ' → Remaining ',
      'solicitados_label': ' requested, ',
      'disponibles_label': ' available',
      // Modal notificaciones
      'notif_msg_activadas': 'Notifications enabled',
      'notif_msg_desactivadas': 'Notifications disabled',
      'notif_msg_silenciadas': 'Notifications muted',
      'error_guardar_config': 'Error saving settings',
      // Modal dirección
      'toca_mapa': 'Tap the map to set your address',
      'direccion_invalida': 'Enter a valid address',
      'direccion_actualizada': 'Address updated successfully',
      'error_actualizar_direccion': 'Error updating address',
      'guardar_cambios': 'Save changes',
      // Nóminas vacaciones
      'acumulados_label': 'accumulated',
      'usados_label': 'used',
      // Dashboard
      'ultima_nomina': 'Latest payslip',
      // Detalle evento
      'ir_chat': 'CHAT',
      'grupo_no_creado': 'GROUP NOT CREATED',
      'grupo_aviso': 'The group has not been created yet',
      'ver_historico': 'VIEW HISTORY',
      'evento_finalizado_lectura': 'Event finished · read only',
      // Perfil nominas
      'ver_mis_nominas': 'View my payslips',
      // Modal idioma
      'idioma_es': 'Spanish',
      'idioma_en': 'English',
      'idioma_cambiado_a': 'Language changed to',
      'error_cambiar_idioma': 'Error changing language',
      // Modal avatar
      'seleccionar_avatar': 'Select avatar',
      'galeria': 'Gallery',
      'camara': 'Camera',
      'avatar_predefinido': 'Or choose a preset avatar',
      'usar_iniciales': 'Use name initials',
      'avatar_actualizado': 'Avatar updated successfully',
      'error_actualizar_avatar': 'Error updating avatar',
      'guardar_avatar': 'Save avatar',
      // Recuperar contraseña
      'recuperar_contrasena': 'Recover password',
      'correo_no_registrado': 'No account found with that email address',
      'correo_enviado_titulo': 'Email sent!',
      'introduce_tu_correo': 'Enter your email address',
      'correo_recibido_desc': 'If the email is registered on our platform, you will receive the instructions in your inbox.',
      'instrucciones_desc': 'We will send you instructions to reset your password.',
      'correo_electronico': 'Email address',
      'ingresa_correo_error': 'Please enter your email',
      'correo_invalido_error': 'Please enter a valid email',
      'enviar_instrucciones': 'Send instructions',
      'redirigiendo_login': 'Redirecting to login...',
      'error_enviar_correo': 'Error sending email. Please try again',
      'error_correo_no_encontrado': 'No account found with that email',
      // Modal editar teléfono
      'editar_telefono': 'Edit phone',
      'numero_telefono': 'Phone number',
      'telefono_digitos_error': 'Enter 9 valid digits',
      'telefono_actualizado': 'Phone updated successfully',
      'error_actualizar_telefono': 'Error updating phone',
      'telefono_info': 'This number will be used to contact you in case of emergencies or last-minute event changes.',
      // Chat - location
      'compartir_ubicacion': 'Share location',
      'ubicacion_compartida': 'Location',
      'abrir_maps': 'Open in Maps',
      'gps_desactivado': 'Location services are disabled',
      'seleccionar_ubicacion': 'Select location',
      'confirmar_ubicacion': 'Confirm & send',
      'adjuntar_imagen': 'Attach image',
      'error_traduccion': 'Translation error. Enable "Cloud Translation API" in Google Cloud Console',
      // Chat - translation
      'traducir_mensajes': 'Translate messages',
      // Chat - interactions (reply, edit, delete)
      'respondiendo_a': 'Replying to',
      'editando_mensaje': 'Editing message',
      'editar': 'Edit',
      'eliminar': 'Delete',
      'confirmar_eliminar': 'Delete this message?',
      'mensaje_editado': 'edited',
      'error_editar': 'Error editing message',
      'error_eliminar': 'Error deleting message',
      // ── Admin panel: shell and sidebar ──
      'admin_panel': 'Admin panel',
      'admin_inicio': 'Home',
      'admin_trabajadores': 'Workers',
      'admin_eventos': 'Events',
      'admin_nominas': 'Payroll',
      'admin_logout_msg': 'Are you sure you want to sign out?',
      // ── Admin panel: dashboard ──
      'admin_resumen': 'Summary',
      'admin_actualizar': 'Refresh',
      'admin_kpi_trabajadores': 'Active workers',
      'admin_kpi_eventos': 'Upcoming events (7 days)',
      'admin_kpi_horas': 'Hours clocked this month',
      'admin_kpi_nominas': 'Payslips pending to send',
      'admin_proximos_eventos': 'Upcoming events',
      'admin_sin_proximos': 'No upcoming events',
      'admin_error_datos': 'Could not load data',
      'admin_reintentar': 'Retry',
      'admin_asignados': 'assigned',
      // ── Admin panel: workers ──
      'w_nuevo': 'New worker',
      'w_error_cargar': 'Error loading workers',
      'w_buscar': 'Search by name…',
      'w_sin_resultados': 'No workers match your search',
      'w_col_nombre': 'NAME',
      'w_col_email': 'EMAIL',
      'w_col_telefono': 'PHONE',
      'w_col_estado': 'STATUS',
      'w_activo': 'Active',
      'w_inactivo': 'Inactive',
      'w_gestionar': 'Manage',
      'w_sin_workers': 'No workers yet',
      'w_crear_primero': 'Create the first one',
      'w_gestionar_titulo': 'Manage worker',
      'w_nombre': 'First name *',
      'w_apellidos': 'Last name',
      'w_telefono': 'Phone',
      'w_dni': 'ID (DNI)',
      'w_activo_toggle': 'Active worker',
      'w_inactivo_toggle': 'Inactive worker',
      'w_campo_obligatorio': 'Required field',
      'w_min_password': 'At least 6 characters',
      'w_formato_telefono': 'Format: 6XXXXXXXX',
      'w_formato_dni': 'Format: 12345678A',
      'w_guardar_cambios': 'Save changes',
      'w_error_guardar': 'Error saving. Please try again.',
      'w_error_eliminar_op': 'Error deleting. Please try again.',
      'w_eliminar_titulo': 'Delete worker',
      'w_eliminar_pre': 'Are you sure you want to delete ',
      'w_eliminar_post': '? This action cannot be undone.',
      'w_datos_ok': 'Details updated successfully',
      'w_eliminado': 'Worker deleted',
      'w_email': 'Email *',
      'w_password': 'Password *',
      'w_crear': 'Create worker',
      'w_err_email_uso': 'That email is already registered.',
      'w_err_email_inv': 'The email is not valid.',
      'w_err_pass_debil': 'The password is too weak.',
      'w_err_crear': 'Error creating the worker. Please try again.',
      'w_creado': 'Worker created',
      'w_email_label': 'Email',
      'w_password_label': 'Password',
      'w_descargar_ticket': 'Download PDF ticket',
      'w_cerrar': 'Close',
      'w_generar_password': 'Generate new password',
      // ── Admin panel: events (list + form) ──
      'ev_estado_borrador': 'Draft',
      'ev_estado_publicado': 'Published',
      'ev_estado_activo': 'Active',
      'ev_estado_finalizado': 'Finished',
      'ev_filtro_todos': 'All',
      'ev_filtro_borradores': 'Drafts',
      'ev_filtro_publicados': 'Published',
      'ev_filtro_activos': 'Active',
      'ev_filtro_finalizados': 'Finished',
      'ev_nuevo': 'New event',
      'ev_error_cargar': 'Error loading events',
      'ev_fecha': 'Date',
      'ev_sin_resultados': 'No events match the filters',
      'ev_confirmados': 'confirmed',
      'ev_pendientes_tooltip': 'Applications pending review',
      'ev_pendiente': 'pending',
      'ev_pendientes': 'pending',
      'ev_editar_tooltip': 'Edit event',
      'ev_eliminar_tooltip': 'Delete event',
      'ev_cambiar_estado': 'Change status',
      'ev_eliminar_titulo': 'Delete event',
      'ev_eliminar_msg': 'Chat messages will be deleted and assigned workers will be notified.',
      'ev_eliminado_pre': 'Event "',
      'ev_eliminado_post': '" deleted',
      'ev_sin_eventos': 'No events yet',
      'ev_crear_primero': 'Create the first one',
      'ev_err_fecha_hora': 'You must select a date and time.',
      'ev_err_duracion': 'Duration must be greater than 0.',
      'ev_err_plaza': 'Define at least one slot in a role.',
      'ev_guard_pre': 'You cannot leave role "',
      'ev_guard_mid': '" below its ',
      'ev_guard_post': ' confirmed members. Increase the slots or remove members first.',
      'ev_err_guardar': 'Could not save the event. Please try again.',
      'ev_editar_titulo': 'Edit event',
      'ev_sec_detalles': 'Event details',
      'ev_campo_nombre': 'Event name *',
      'ev_campo_desc': 'Description (optional)',
      'ev_campo_ubicacion': 'Location *',
      'ev_campo_duracion': 'Duration (h) *',
      'ev_crear_evento': 'Create event',
      'ev_sec_plazas': 'Slots per role',
      'ev_plazas_help': 'How many workers do you need for each role?',
      'ev_sec_estado': 'Status',
      'ev_fecha_req': 'Date *',
      'ev_hora_req': 'Time *',
      'ev_marcado_pre': 'Event marked as ',
      'ev_err_estado': 'Could not change the status',
      'ev_volver': 'Back to the list',
      'ev_quitar_fecha': 'Clear date filter',
      'ev_ver_postulaciones': 'View applications',
      'ev_ver_fichajes': 'View clock-ins',
      // ── Admin panel: applications / team management ──
      'pl_volver': 'Back',
      'pl_titulo': 'Applications',
      'pl_confirmados_sec': 'CONFIRMED',
      'pl_pendientes_sec': 'PENDING',
      'pl_anadir': 'Add member',
      'pl_anadir_btn': 'Add',
      'pl_ver_historico': 'View chat history',
      'pl_abrir_chat': 'Open group chat',
      'pl_chat_no_disp': 'Chat unavailable (group not created)',
      'pl_sin_pendientes': 'No pending applications',
      'pl_sin_confirmados': 'No one confirmed yet',
      'pl_quitar': 'Remove',
      'pl_quitar_titulo': 'Remove member',
      'pl_quitar_pre': 'Remove ',
      'pl_quitar_post': ' from the event? Their slot will be freed and their application discarded.',
      'pl_quitado': 'Member removed',
      'pl_err_quitar': 'Could not remove',
      'pl_sin_plazas': 'No free slots; edit the event to add slots',
      'pl_sin_workers': 'No more workers to add',
      'pl_trabajador_label': 'Worker',
      'pl_rol_label': 'Role (with a free slot)',
      'pl_anadido': 'Member added',
      'pl_rol_completo': 'Role full; edit the event to add slots',
      'pl_err_anadir': 'Could not add',
      'pl_trabajador': 'Worker',
      'pl_descartar': 'Discard',
      'pl_confirmar': 'Confirm',
      'pl_confirmado_ok': 'Worker confirmed',
      'pl_err_confirmar': 'Could not confirm',
      'pl_descartada': 'Application discarded',
      'pl_err_descartar': 'Could not discard',
      'pl_sin_plazas_evento': 'This event does not define slots per role.',
      'pl_confirmados_conteo': 'confirmed',
      // Group activation (activar_evento.dart)
      'pl_crear_grupo': 'Create group',
      'pl_activar_completo': 'The team is complete. The group will be created and the event will become active (it leaves the feed and the chat opens).',
      'pl_activar_faltan': 'There are still slots to fill:',
      'pl_faltan': 'missing',
      'pl_activar_pregunta': 'Create the group anyway? The event will leave the feed.',
      'pl_grupo_creado': 'Group created: event active',
      'pl_err_crear_grupo': 'Could not create the group',
      // ── Admin panel: payroll ──
      'nom_calculando': 'Calculating hours and salaries…',
      'nom_mes': 'Month',
      'nom_anio': 'Year',
      'nom_calcular': 'Calculate',
      'nom_instr1': 'Select a month and press "Calculate"',
      'nom_instr2': 'You will see which workers clocked in that month\nand you can send them their payslip.',
      'nom_sin_trabajo': 'No worker clocked in in',
      'nom_sin_trabajo2': 'Only workers with finished clock-ins that month are shown.',
      'nom_trabajadores_en': 'worker(s) in',
      'nom_visible': "Sent payslips are visible in the worker's app.",
      'nom_enviar_todas': 'Send all',
      'nom_todas_enviadas': 'All sent',
      'nom_trabajadas': 'worked',
      'nom_eventos_count': 'event(s)',
      'nom_neto': 'net',
      'nom_bruto': 'gross',
      'nom_enviar': 'Send payslip',
      'nom_descargar_tooltip': 'Download PDF without sending',
      'nom_bruto_label': 'Gross:',
      'nom_neto_label': 'Net:',
      'nom_deducciones': 'Income tax 15% + Social Security 6.35%',
      'nom_enviada_pre': 'Payslip for ',
      'nom_enviada_post': ' sent successfully',
    },
  };

  static String tr(String idioma, String clave) {
    return _t[idioma]?[clave] ?? _t['es']?[clave] ?? clave;
  }
}
